# Utilizar una imagen base ligera de Nginx
FROM nginx:alpine

# Copiar el archivo index.html a la carpeta de Nginx
COPY index.html /usr/share/nginx/html/

# Exponer el puerto 80 para el servidor
EXPOSE 80

# Comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
